
credentials:
  usernames:
    student1:
      name: Student One
      password: pbkdf2:sha256:260000$yLqjRnOXzAq0bPiK$0ed5f30e01bcf8e2bc7dc50cb52864be267f57b4fa1d3485285c3574f79c7d70
cookie:
  name: tutor_app_cookie
  key: some_random_key
  expiry_days: 1
